
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: checkoutservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.2
          ports:
          - containerPort: 5050
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.microservices-productcatalog.svc.cluster.local:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.microservices-shipping.svc.cluster.local:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.microservices-payment.svc.cluster.local:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.microservices-email.svc.cluster.local:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.microservices-currency.svc.cluster.local:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.microservices-cart.svc.cluster.local:7070"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice